// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/clients","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"客户端管理","path":"/clients","icon":"AppstoreOutlined","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"API 资源","path":"/api-resources","icon":"ApiOutlined","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"API 作用域","path":"/api-scopes","icon":"SafetyOutlined","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"Identity 资源","path":"/identity-resources","icon":"UserOutlined","parentId":"ant-design-pro-layout","id":"5"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Clients__index" */'@/pages/Clients/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__ApiResources__index" */'@/pages/ApiResources/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__ApiScopes__index" */'@/pages/ApiScopes/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__IdentityResources__index" */'@/pages/IdentityResources/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'G:/EasilyNET.IdentityServer/src/EasilyNET.IdentityServer.Admin/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
