// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import AppstoreOutlined from 'G:/EasilyNET.IdentityServer/src/EasilyNET.IdentityServer.Admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/AppstoreOutlined';
import ApiOutlined from 'G:/EasilyNET.IdentityServer/src/EasilyNET.IdentityServer.Admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ApiOutlined';
import SafetyOutlined from 'G:/EasilyNET.IdentityServer/src/EasilyNET.IdentityServer.Admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/SafetyOutlined';
import UserOutlined from 'G:/EasilyNET.IdentityServer/src/EasilyNET.IdentityServer.Admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/UserOutlined';
export default { AppstoreOutlined, ApiOutlined, SafetyOutlined, UserOutlined };
